describe:
  auto: false
  exclude:
    - "test/baselines/**/*"
review:
  exclude:
    - "test/baselines/**/*"
gentest:
  exclude:
    - "test/baselines/**/*"
suggest:
  exclude:
    - "test/baselines/**/*"
    - "test/old-examples/**/*"
    - "test/old-issues/**/*"
    - "test/scores/**/*"
    - "test/util/data/**/*"
    - ".github/**/*"
    - ".husky/**/*"
    - ".vscode/**/*"
    - "end_to_end/**/*"
    - "docs/**/*"
    - "prompt/**/*"
    - "scorer/**/*"
    - ".dockerignore"
    - ".env.example"
    - ".eslintrc"
    - ".eslintignore"
    - ".gitignore"
    - ".prettierrc"
    - "*.md"
    - "LICENSE"
    - "app.yml"
    - "jest.config.js"
    - "package.json"
    - "package-lock.json"
    - "prbot"
    - "prbot-engine"
summarize:
  exclude:
    - "test/baselines/**/*"
    - "test/old-examples/**/*"
    - "test/old-issues/**/*"
    - "test/scores/**/*"
    - "test/util/data/**/*"
    - ".github/**/*"
    - ".husky/**/*"
    - ".vscode/**/*"
    - "end_to_end/**/*"
    - "docs/**/*"
    - "prompt/**/*"
    - "scorer/**/*"
    - ".dockerignore"
    - ".env.example"
    - ".eslintrc"
    - ".eslintignore"
    - ".gitignore"
    - ".prettierrc"
    - "*.md"
    - "LICENSE"
    - "app.yml"
    - "jest.config.js"
    - "package.json"
    - "package-lock.json"
    - "prbot"
    - "prbot-engine"
